apiVersion: apps/v1
kind: Deployment
metadata:
  name: ok
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ok
  template:
    metadata:
      labels:
        app: ok
    spec:
      containers:
      - image: okteto.dev/ok:latest
        name: ok
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "d4d2f2d8-af54-42c1-aa29-c8289b6f1267"
        - name: Vless_Path
          value: "/asdsadj37"
        - name: Vmess_UUID
          value: "d4d2f2d8-af54-42c1-aa29-c8289b6f1267"
        - name: Vmess_Path
          value: "/asdq324245"
        - name: Share_Path
          value: "/v2link"
